### ISSUE TITLE
normal text invisible in dark mode

### ISSUE THREAD

**Issue by RiverCrimea** [Craiel/ArcanumScript#4]
Resources on the left panel are hard-coded to appear as `style="color: rgb(0, 0, 0);"`.
While this works fabulously on a white background, it has the effect of rendering the text almost completely invisible in dark mode, as seen on the "Herbs" line in the attached screenshot.

![ToM - script dark mode](https://user-images.githubusercontent.com/7605946/87213991-bdc48780-c2ee-11ea-9f9a-89a9daeb609d.png)

**Comment by RiverCrimea** [comment]
Would it be possible to add a `.css` file to the code? Not to replace the game's `main.css`, but to augment it.
The primary goal would be to eliminate the inline css in the script's code. That would make the code cleaner, and it would make it relatively easy to fix this issue, as well.

If it is possible, I am happy to do the work of creating it and testing it.

**Comment by Craiel** [comment]
Hello, sorry for the delay on this. I updated the script today to work for 0.8.0 and also addressed this. Let me know if that fixes the issue

**Comment by RiverCrimea** [comment]
Thank you for waiting for my response before closing the issue. Yes, it works now.
